### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by piecioshka** [sjsyrek/MonadJS#1]
Hi @sjsyrek 

please split implementation and tests to others files.

**Comment by sjsyrek** [comment]
You could submit a pull request, if you like, though I am working on a more extensive library that will contain an implementation of Monad (among other structures) in ES2015, complete with tests.

**Comment by sjsyrek** [comment]
Published! Check it out: 

https://github.com/sjsyrek/maryamyriameliamurphies.js
https://www.npmjs.com/package/maryamyriameliamurphies

**Comment by piecioshka** [comment]
Nice! 💪
